update website
stevenhwu/stevenhwu.github.io pull request #50
Opened 2024-03-01 09:20 UTC by yuhanwu0302

Hi, Steven I just updated my personal page picture.

2024-03-01 09:41 UTC, stevenhwu requested changes
can you please rename the image to `yu_han_wu`?
I try to keep the naming convention, so it will be easier fro me to manage in the long run.

2024-03-04 05:27 UTC, stevenhwu requested changes

2024-03-04 05:27 UTC, stevenhwu commented on people.md
> +<img src="{{base.url}}/img/Yu-Han.jpg" alt="Yu-Han Wu" align="left" hspace="50" width="25%">
```suggestion
<img src="{{base.url}}/img/yu_han_wu.jpg" alt="Yu-Han Wu" align="left" hspace="50" width="25%">
```

2024-03-04 05:27 UTC, stevenhwu commented on personal_page/yu_han_wu.md
> +<img src="{{site.url}}/img/Yu-Han.jpg" align="left" hspace="10" width="25%">
```suggestion
<img src="{{base.url}}/img/yu_han_wu.jpg" alt="Yu-Han Wu" align="left" hspace="50" width="25%">
```

2024-03-05 03:11 UTC, yuhanwu0302 commented on people.md
> +<img src="{{base.url}}/img/Yu-Han.jpg" alt="Yu-Han Wu" align="left" hspace="50" width="25%">
oops, I forgot to revise this! sorry!

2024-03-05 03:39 UTC, stevenhwu approved these changes
Merge it please.

2024-03-05 04:39 UTC, yuhanwu0302 commented
> Merge it please.

Steven, I see this message "Only those with [write access](https://docs.github.com/articles/what-are-the-different-access-permissions) to this repository can merge pull requests."

2024-03-05 13:50 UTC, merged