update profile
stevenhwu/stevenhwu.github.io pull request #53
Opened 2024-03-08 03:48 UTC by mercur0us

2024-03-08 05:34 UTC, stevenhwu requested changes
I think that might be better to make GitHub a proper link.

2024-03-08 05:34 UTC, stevenhwu commented on personal_page/kayleen_howen.md
> +><i class="fab fa-github"></i> [Github](mercur0us)  
```suggestion
><i class="fab fa-github"></i> [Github](https://github.com/mercur0us)  
```

2024-03-20 11:01 UTC, stevenhwu commented on personal_page/kayleen_howen.md
> +><i class="fab fa-github"></i> [Github](mercur0us)  
@mercur0us Ok with this?

2024-03-22 02:24 UTC, mercur0us commented
sorry for the late reply. Yes that's ok!

On Wed, Mar 20, 2024 at 7:01 PM Steven Wu ***@***.***> wrote:

> ***@***.**** commented on this pull request.
> ------------------------------
>
> In personal_page/kayleen_howen.md
> <https://github.com/stevenhwu/stevenhwu.github.io/pull/53#discussion_r1531885905>
> :
>
> > @@ -9,28 +9,35 @@ show_sidebar: false
>
>  ## Kayleen Howen
>
> -<img src="{{site.url}}/img/random.jpg" align="left" hspace="10" width="25%">
> -
> -Contact:
> -<i class="fas fa-at"></i> [Email](mailto:)
> -
> +<img src="{{site.url}}/img/kayleen_howen.jpg" align="left" hspace="10" width="25%">
> +</br>
> +An Indonesian junior student currently studying agronomy at National Taiwan University. Eager to learn but procastinates too much somtimes.
> +<br>
> +
> +#### Contact:
> +><i class="fas fa-at"></i> ***@***.***)
> + <br clear="all">
> +><i class="fab fa-github"></i> [Github](mercur0us)
>
> @mercur0us <https://github.com/mercur0us> Ok with this?
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/stevenhwu/stevenhwu.github.io/pull/53#discussion_r1531885905>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AZFU5TSVVZYIV2R5SMWAWJ3YZFUAVAVCNFSM6AAAAABEMEVCNCVHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMYTSNBYGU3DINZRGM>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2024-03-22 06:26 UTC, stevenhwu approved these changes

2024-03-22 06:26 UTC, merged